### ISSUE TITLE
Error: Json Value of type 'Null' used as a 'Array' (or 'Object')

### ISSUE THREAD

**Issue by Xiaoguang-Guo** [KellanM/OpenAI-Api-Unreal#20] opened 2023-03-09 05:32 UTC
My blueprint is built like this and it's getting some errors. I don't know how to fix it, because I can't find which line they are reporting the error on.

![image](https://user-images.githubusercontent.com/91207209/223928734-de0437ba-43f6-4477-8224-512feb3076a6.png)

Log
`
....
LogTemp: Warning: {"id":"----------------","object":"text_completion","created":1678339481,"model":"davinci","choices":[{"text":" I watched <movie>.\n","index":0,"logprobs":null,"finish_reason":"stop"}],"usage":{"prompt_tokens":31,"completion_tokens":6,"total_tokens":37}}

LogJson: Warning: Field logprobs is of the wrong type.

LogJson: Error: Json Value of type 'Null' used as a 'Object'.

LogJson: Warning: Field logprobs is of the wrong type.

LogJson: Error: Json Value of type 'Null' used as a 'Object'.

LogJson: Warning: Field tokens was not found.

LogJson: Error: Json Value of type 'Null' used as a 'Array'.

LogJson: Warning: Field token_logprobs was not found.

LogJson: Error: Json Value of type 'Null' used as a 'Array'.

LogJson: Warning: Field text_offset was not found.

LogJson: Error: Json Value of type 'Null' used as a 'Array'.

LogBlueprintUserMessages: [Char_C_0]  I watched <movie>.

....
`

**Comment by KellanM** [comment] 2023-04-03 04:20
removed log probs since I don't think anyone actually uses them 😅. Let me know if this fixes your issue!

**Comment by KellanM** [comment] 2023-04-03 04:22
Duplicate of issue #9 . Closing

**Closed by KellanM** 2023-04-03 04:22 UTC

**Comment by qingmuyu** [comment] 2023-09-28 01:01
您好，请问解决了吗
